# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/db_absensi?useSSL=false&serverTimezone=Asia/Jakarta&allowPublicKeyRetrieval=true
spring.datasource.username=absensi
spring.datasource.password=absensi
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER
# ===============================

server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.whitelabel.enabled=false

# ===============================
# TIMEZONE & JSON
# ===============================

spring.datasource.hikari.connection-init-sql=SET time_zone = '+07:00'
spring.jackson.time-zone=Asia/Jakarta
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# ===============================
# LOGGING
# ===============================

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.file.name=logs/absensi.log



# ================= JWT CONFIG =================

# ? Secret & Issuer
jwt.secret=${JWT_SECRET:K2x9Z3pQeGJtT3FzZVJpY2tTb2x1dGlvblNlY3JldEtleTEyMzQ1Ng==}
jwt.issuer=${JWT_ISSUER:absensiv2-app}

# ? Access Token (detik)
jwt.access-token.ttl-seconds=${JWT_ACCESS_TTL:3600}

# ? Refresh Token (detik)
jwt.refresh-token.ttl-seconds=${JWT_REFRESH_TTL:86400}

# ? Cookie untuk Refresh Token
jwt.cookie.name=${JWT_REFRESH_COOKIE_NAME:refreshToken}
jwt.cookie.secure=${JWT_COOKIE_SECURE:true}
jwt.cookie.http-only=${JWT_COOKIE_HTTP_ONLY:true}
jwt.cookie.same-site=${JWT_COOKIE_SAME_SITE:lax}


# ================= VERIFIKASI EMAIL CONFIG =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=webbranding6@gmail.com
spring.mail.password=ddizthjqtforgmfx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true